version: "2"
services:
    nginx:
        image: nginx:1.12.0
        ports:
            - "80:80"
        depends_on:
            - php
            - mysql
            - redis
            - beanstalkd
        volumes_from:
            - php
            - mysql
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./services/nginx/conf.d:/etc/nginx/conf.d
            - ./data/nginx/:/var/log/nginx/
        working_dir: /etc/nginx/conf.d
    php:
        build:
            context: ./services/php
            dockerfile: Dockerfile
        depends_on:
            - mysql
            - redis
            - beanstalkd
            - mongo
        volumes:
            - ./services/php/cron:/etc/cron.d
            - ./services/php/supervisor:/etc/supervisor/conf.d
            - ./wwwroot:/home/wwwroot
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "php7"
            MYSQL_PASSWORD: "php7"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./services/mysql/my.cnf:/etc/mysql/my.cnf
    redis:
        image: redis:3.2.9
        ports:
            - "6379:6379"
    beanstalkd:
        build:
            context: ./services/beanstalkd
            dockerfile: Dockerfile
    mongo:
        image: mongo:3.4
        environment:
          - MONGO_DATA_DIR=/data/mongodb
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/mongo:/data/mongodb
        ports:
            - "27017:27017"
